name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions with npm and node.js
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: npm install
      - run: npm run build
      - run: echo "Hello, world!"
